import { AppLanguage } from "../middleware";

export const supportedLanguages = {
  [AppLanguage.English]: {
    code: AppLanguage.English,
    name: "English",
    shortName: "EN",
    direction: "ltr",
    isLeftDirection: true,
    locale: "en",
  },
  [AppLanguage.Arabic]: {
    code: AppLanguage.Arabic,
    name: "العربية",
    shortName: "عربي",
    direction: "rtl",
    isLeftDirection: false,
    font: "font-kufi",
    locale: "ar",
  },
  [AppLanguage.Pashto]: {
    code: AppLanguage.Pashto,
    name: "پښتو",
    shortName: "پښتو",
    direction: "rtl",
    isLeftDirection: false,
    locale: "ps",
  },
  [AppLanguage.korean]: {
    code: AppLanguage.korean,
    name: "한국어",
    shortName: "한국어",
    direction: "ltr",
    isLeftDirection: true,
    locale: "ko",
  },
  [AppLanguage.Farsi]: {
    code: AppLanguage.Farsi,
    name: "فارسی",
    shortName: "فا",
    direction: "rtl",
    isLeftDirection: false,
    font: "font-kufi",
    locale: "fa",
  },
  [AppLanguage.Chinese]: {
    code: AppLanguage.Chinese,
    name: "中文",
    shortName: "中",
    direction: "ltr",
    isLeftDirection: true,
    locale: "zh",
  },
  [AppLanguage.Italian]: {
    code: AppLanguage.Italian,
    name: "Italiano",
    shortName: "IT",
    direction: "ltr",
    isLeftDirection: true,
    locale: "it",
  },
  [AppLanguage.Melayu]: {
    code: AppLanguage.Melayu,
    name: "Melayu",
    shortName: "MY",
    direction: "ltr",
    isLeftDirection: true,
    locale: "ms",
  },
  [AppLanguage.Hindi]: {
    code: AppLanguage.Hindi,
    name: "हिन्दी",
    shortName: "हि",
    direction: "ltr",
    isLeftDirection: true,
    locale: "hi",
  },
  [AppLanguage.Indonasian]: {
    code: AppLanguage.Indonasian,
    name: "Bahasa Indonesia",
    shortName: "ID",
    direction: "ltr",
    isLeftDirection: true,
    locale: "id",
  },
  [AppLanguage.French]: {
    code: AppLanguage.French,
    name: "Français",
    shortName: "FR",
    direction: "ltr",
    isLeftDirection: true,
    locale: "fr",
  },
  [AppLanguage.Spanish]: {
    code: AppLanguage.Spanish,
    name: "Español",
    shortName: "ES",
    direction: "ltr",
    isLeftDirection: true,
    locale: "es",
  },
  [AppLanguage.Japanese]: {
    code: AppLanguage.Japanese,
    name: "日本語",
    shortName: "JP",
    direction: "ltr",
    isLeftDirection: true,
    locale: "ja",
  },
  [AppLanguage.Vitenam]: {
    code: AppLanguage.Vitenam,
    name: "Tiếng Việt",
    shortName: "VI",
    direction: "ltr",
    isLeftDirection: true,
    locale: "vi",
  },
  [AppLanguage.Philippines]: {
    code: AppLanguage.Philippines,
    name: "Tagalog",
    shortName: "tl",
    direction: "ltr",
    isLeftDirection: true,
    locale: "tl",
  },
  [AppLanguage.Urdu]: {
    code: AppLanguage.Urdu,
    name: "Urdu",
    shortName: "ur",
    direction: "rtl",
    isLeftDirection: false,
    font: "font-kufi",
    locale: "ur",
  },
  [AppLanguage.português]: {
    code: AppLanguage.português,
    name: "Português",
    shortName: "pt",
    direction: "ltr",
    isLeftDirection: true,
    locale: "pt",
  },
  [AppLanguage.Thailand]: {
    code: AppLanguage.Thailand,
    name: "ไทย",
    shortName: "th",
    direction: "ltr",
    isLeftDirection: true,
    locale: "th",
  },
  [AppLanguage.Russian]: {
    code: AppLanguage.Russian,
    name: "Русский",
    shortName: "ru",
    direction: "ltr",
    isLeftDirection: true,
    locale: "ru",
  },
  [AppLanguage.Chinese_Traditional]: {
    code: AppLanguage.Chinese_Traditional,
    name: "繁體中文",
    shortName: "zh-tw",
    direction: "ltr",
    isLeftDirection: true,
    locale: "zh-tw",
  },
};
